### ISSUE TITLE
Download link on another platform

### ISSUE THREAD

**Issue by diegoantognini** [Junjieli0704/USN#1]
Dear authors,

Thank you very much to have shared the dataset used in your recent AAAI paper. I was wondering if you could upload the dataset on a different platform than Baidu ? The process to download the dataset since complicate: pages in chinese, mobile phone as to be provided to create an account, download baidu software is necessary etc.

Thank you in advance for your help.

Best,

**Comment by Junjieli0704** [comment]
Sorry to reply so late, please see https://nbccadminedupl-my.sharepoint.com/personal/junnanzhu_x2_tn/Documents/Forms/All.aspx?cid=85296f84-8928-4693-87cf-8069b5b52eb6&RootFolder=%2Fpersonal%2Fjunnanzhu_x2_tn%2FDocuments%2FAAAI19-Trip&FolderCTID=0x012000B389F9BADD07EF44B744EC0C9C15F430
